steps:
- name: 'openjdk:8-jdk'
  entrypoint: 'bash'
  args: ['-c', './mvnw clean package']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '-t', 'eu.gcr.io/$PROJECT_ID/tesk-api:$TAG_NAME',
         '-f', 'Dockerfile', '.']
images:
- 'eu.gcr.io/$PROJECT_ID/tesk-api:$TAG_NAME'