steps:
- name: 'openjdk:8-jdk-alpine'
  entrypoint: 'sh'
  args: ['-c', './mvnw clean verify']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '-t', 'eu.gcr.io/$PROJECT_ID/tesk-api:$TAG_NAME',
         '-f', 'Dockerfile', '.']
images:
- 'eu.gcr.io/$PROJECT_ID/tesk-api:$TAG_NAME'